---
ENV: production

nginx_server_name: "avere.elbear.com"
nginx_static_path: "{{ site_deployment_path }}/{{ site_dir_name }}/static_all"
nginx_templates_path: "{{ site_deployment_path }}/{{ site_dir_name }}/templates"

site_secret_key:
site_allowed_hosts: "{{ nginx_server_name }},"
